import { FormTemplate } from "./types";

export const TEMPLATES: FormTemplate[] = [
  {
    id: "retro",
    theme: "retro",
    name: "Wizard's Quest",
    tagline: "A pixel-art sign-up scroll guarded by a wand-waving mage.",
    title: "JOIN THE GUILD",
    description: "Fill the scroll to begin your quest, brave adventurer.",
    submitLabel: "PRESS START",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "hero_name",
        type: "text",
        label: "Hero Name",
        placeholder: "Sir Pixelot",
        required: true,
      },
      {
        id: "class",
        type: "select",
        label: "Choose Your Class",
        required: true,
        options: ["Warrior", "Mage", "Ranger", "Bard", "Rogue"],
      },
      {
        id: "power_level",
        type: "number",
        label: "Power Level",
        placeholder: "9000",
      },
      {
        id: "quest",
        type: "textarea",
        label: "Why do you seek glory?",
        placeholder: "To slay the great bug boss...",
      },
      {
        id: "newsletter",
        type: "checkbox",
        label: "Send me carrier-pigeon updates",
      },
    ],
  },
  {
    id: "terminal",
    theme: "terminal",
    name: "root@access",
    tagline: "A hacker terminal boot sequence that types itself out.",
    title: "SECURE ACCESS REQUEST",
    description: "Authenticate to gain access to the mainframe.",
    submitLabel: "> EXECUTE",
    showSvgBackground: true,
    showHeaderGraphic: false,
    fields: [
      {
        id: "username",
        type: "text",
        label: "username",
        placeholder: "neo",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "email",
        placeholder: "operator@matrix.io",
        required: true,
      },
      {
        id: "clearance",
        type: "radio",
        label: "clearance_level",
        required: true,
        options: ["guest", "operator", "sysadmin", "root"],
      },
      {
        id: "payload",
        type: "textarea",
        label: "message_payload",
        placeholder: "echo 'hello world'",
      },
    ],
  },
  {
    id: "autumn",
    theme: "autumn",
    name: "Harvest RSVP",
    tagline: "Cozy warm tones with pixel leaves drifting across the page.",
    title: "Autumn Gathering",
    description: "Join us for cider, bonfires, and falling leaves.",
    submitLabel: "Save my spot 🍂",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "guest_name",
        type: "text",
        label: "Your Name",
        placeholder: "Autumn Leaf",
        required: true,
      },
      {
        id: "attending",
        type: "radio",
        label: "Will you attend?",
        required: true,
        options: ["Yes, count me in!", "Maybe", "Sadly, no"],
      },
      {
        id: "guests",
        type: "number",
        label: "Number of guests",
        placeholder: "2",
      },
      {
        id: "date",
        type: "date",
        label: "Preferred date",
      },
      {
        id: "dish",
        type: "select",
        label: "What will you bring?",
        options: ["Pumpkin pie", "Apple cider", "Roasted chestnuts", "Nothing, just vibes"],
      },
      {
        id: "notes",
        type: "textarea",
        label: "Anything else?",
        placeholder: "I love this season because...",
      },
    ],
  },
  {
    id: "nerdy",
    theme: "nerdy",
    name: "Lab Notebook",
    tagline: "Graph-paper science journal with hand-scribbled doodles.",
    title: "Research Enrollment",
    description: "Submit your hypothesis to the experiment cohort.",
    submitLabel: "Submit hypothesis",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "researcher",
        type: "text",
        label: "Researcher name",
        placeholder: "Ada Lovelace",
        required: true,
      },
      {
        id: "field",
        type: "select",
        label: "Field of study",
        required: true,
        options: ["Physics", "Chemistry", "Biology", "Computer Science", "Mathematics"],
      },
      {
        id: "hypothesis",
        type: "textarea",
        label: "State your hypothesis",
        placeholder: "If X, then Y because...",
        required: true,
      },
      {
        id: "coffee",
        type: "number",
        label: "Cups of coffee per day",
        placeholder: "4",
      },
      {
        id: "peer_review",
        type: "checkbox",
        label: "I agree to peer review",
      },
    ],
  },
  {
    id: "neon",
    theme: "neon",
    name: "Neon Nights",
    tagline: "80s synthwave RSVP with a glowing sun and a scrolling neon grid.",
    title: "NEON NIGHTS",
    description: "RSVP for the retro-future rave of the decade.",
    submitLabel: "Enter the grid",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your name",
        placeholder: "Max Voltage",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email",
        placeholder: "you@retrowave.fm",
        required: true,
      },
      {
        id: "vibe",
        type: "select",
        label: "Pick your vibe",
        required: true,
        options: ["Outrun", "Vaporwave", "Cyberpunk", "Miami sunset"],
      },
      {
        id: "synth",
        type: "radio",
        label: "Bringing a synth?",
        options: ["Yes, obviously", "Just my glowsticks", "No"],
      },
      {
        id: "track",
        type: "textarea",
        label: "Your dream track to hear",
        placeholder: "Something with a lot of reverb...",
      },
    ],
  },
  {
    id: "cosmic",
    theme: "cosmic",
    name: "Mission Control",
    tagline: "A deep-space crew application under a field of twinkling stars.",
    title: "CREW APPLICATION",
    description: "Apply to join the next deep-space expedition.",
    submitLabel: "Launch application 🚀",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Full name",
        placeholder: "Sally Ride",
        required: true,
      },
      {
        id: "callsign",
        type: "text",
        label: "Call sign",
        placeholder: "Nova",
        required: true,
      },
      {
        id: "role",
        type: "select",
        label: "Mission role",
        required: true,
        options: ["Commander", "Pilot", "Engineer", "Science officer", "Medic"],
      },
      {
        id: "destination",
        type: "radio",
        label: "Preferred destination",
        options: ["The Moon", "Mars", "Europa", "Beyond the belt"],
      },
      {
        id: "training",
        type: "number",
        label: "Years of training",
        placeholder: "5",
      },
      {
        id: "why",
        type: "textarea",
        label: "Why do you want to explore space?",
        placeholder: "Ever since I looked up at the stars...",
      },
    ],
  },
  {
    id: "ocean",
    theme: "ocean",
    name: "Deep Dive Log",
    tagline: "A dive-trip booking with bubbles drifting up through the water.",
    title: "Deep Dive Booking",
    description: "Reserve your spot on the next reef expedition.",
    submitLabel: "Book my dive 🐠",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "diver",
        type: "text",
        label: "Diver name",
        placeholder: "Marina Waters",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email",
        placeholder: "diver@deepblue.com",
        required: true,
      },
      {
        id: "level",
        type: "select",
        label: "Experience level",
        required: true,
        options: ["Beginner", "Open water", "Advanced", "Divemaster"],
      },
      {
        id: "date",
        type: "date",
        label: "Preferred dive date",
      },
      {
        id: "depth",
        type: "number",
        label: "Comfortable depth (meters)",
        placeholder: "18",
      },
      {
        id: "certified",
        type: "checkbox",
        label: "I hold a valid diving certification",
      },
    ],
  },
  {
    id: "comic",
    theme: "comic",
    name: "Hero Registration",
    tagline: "Bold pop-art hero sign-up with halftone dots and comic bursts.",
    title: "HERO SIGN-UP!",
    description: "Register your alter-ego with the League.",
    submitLabel: "KAPOW! Register",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "alias",
        type: "text",
        label: "Hero alias",
        placeholder: "Captain Comet",
        required: true,
      },
      {
        id: "power",
        type: "select",
        label: "Primary superpower",
        required: true,
        options: ["Flight", "Super strength", "Invisibility", "Telekinesis", "Time control"],
      },
      {
        id: "origin",
        type: "textarea",
        label: "Origin story",
        placeholder: "It all started when...",
        required: true,
      },
      {
        id: "sidekick",
        type: "radio",
        label: "Do you have a sidekick?",
        options: ["Yes", "No", "Working on it"],
      },
      {
        id: "cape",
        type: "checkbox",
        label: "Cape included (no capes?!)",
      },
    ],
  },
  {
    id: "winter",
    theme: "winter",
    name: "Winter Wonderland",
    tagline: "A frosted-glass RSVP with snow drifting through a night sky.",
    title: "Winter Gala",
    description: "Join us for an evening of snow, lights, and warm cider.",
    submitLabel: "Reserve my seat ❄",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your name",
        placeholder: "Jack Frost",
        required: true,
      },
      {
        id: "attending",
        type: "radio",
        label: "Will you brave the cold?",
        required: true,
        options: ["Yes, bundled up!", "Maybe", "Too chilly for me"],
      },
      {
        id: "guests",
        type: "number",
        label: "Number of guests",
        placeholder: "2",
      },
      {
        id: "drink",
        type: "select",
        label: "Warm drink of choice",
        options: ["Hot cocoa", "Mulled wine", "Spiced cider", "Peppermint tea"],
      },
      {
        id: "wish",
        type: "textarea",
        label: "A winter wish",
        placeholder: "This season I hope for...",
      },
    ],
  },
  {
    id: "birthday",
    theme: "birthday",
    name: "Birthday Bash",
    tagline: "Bright party invite with balloons and confetti raining down.",
    title: "You're Invited! 🎉",
    description: "Let's celebrate — cake, games, and good vibes.",
    submitLabel: "Count me in! 🎈",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your name",
        placeholder: "Party Animal",
        required: true,
      },
      {
        id: "rsvp",
        type: "radio",
        label: "Can you make it?",
        required: true,
        options: ["Absolutely!", "Wouldn't miss it", "Can't come 😢"],
      },
      {
        id: "guests",
        type: "number",
        label: "Plus how many?",
        placeholder: "1",
      },
      {
        id: "cake",
        type: "select",
        label: "Cake preference",
        options: ["Chocolate", "Vanilla", "Red velvet", "Ice cream cake"],
      },
      {
        id: "song",
        type: "text",
        label: "A song for the playlist",
        placeholder: "Add your banger",
      },
    ],
  },
  {
    id: "kawaii",
    theme: "kawaii",
    name: "Kawaii Corner",
    tagline: "Pastel cuteness overload with hearts floating up the screen.",
    title: "Join the Cute Club ♡",
    description: "Sign up for the sweetest little community.",
    submitLabel: "Yay, sign me up! ♡",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your name",
        placeholder: "Mochi",
        required: true,
      },
      {
        id: "email",
        type: "email",
        label: "Email",
        placeholder: "cutie@kawaii.co",
        required: true,
      },
      {
        id: "fav",
        type: "select",
        label: "Favorite cute thing",
        options: ["Kittens", "Bubble tea", "Plushies", "Stickers", "Mochi"],
      },
      {
        id: "mood",
        type: "radio",
        label: "Today's mood",
        options: ["Happy ♡", "Sleepy", "Excited!", "Cozy"],
      },
      {
        id: "note",
        type: "textarea",
        label: "Leave a sweet note",
        placeholder: "Have a lovely day~",
      },
    ],
  },
  {
    id: "western",
    theme: "western",
    name: "Wanted Poster",
    tagline: "Weathered saloon parchment with desert dust drifting past.",
    title: "WANTED",
    description: "Post a bounty or join the posse, partner.",
    submitLabel: "Round 'em up",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Outlaw name",
        placeholder: "Dead-Eye Dan",
        required: true,
      },
      {
        id: "role",
        type: "select",
        label: "Your role in town",
        required: true,
        options: ["Sheriff", "Bounty hunter", "Outlaw", "Saloon keeper", "Prospector"],
      },
      {
        id: "bounty",
        type: "number",
        label: "Bounty ($)",
        placeholder: "500",
      },
      {
        id: "crime",
        type: "textarea",
        label: "Last known deed",
        placeholder: "Robbed the noon train and vanished...",
      },
      {
        id: "reward",
        type: "checkbox",
        label: "Dead or alive",
      },
    ],
  },
  {
    id: "noir",
    theme: "noir",
    name: "Detective Case File",
    tagline: "Black-and-white case file under a slow sweeping spotlight.",
    title: "CASE FILE",
    description: "Report the details. The city never sleeps.",
    submitLabel: "File the report",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your name",
        placeholder: "Sam Spade",
        required: true,
      },
      {
        id: "case_type",
        type: "select",
        label: "Type of case",
        required: true,
        options: ["Missing person", "Theft", "Fraud", "Cold case", "Other"],
      },
      {
        id: "when",
        type: "date",
        label: "Date of incident",
      },
      {
        id: "suspects",
        type: "number",
        label: "Number of suspects",
        placeholder: "1",
      },
      {
        id: "statement",
        type: "textarea",
        label: "Your statement",
        placeholder: "It was a rainy night when...",
        required: true,
      },
    ],
  },
];

/**
 * Two extra variants per theme — same look, different use-case. These power the
 * "hover to cycle variants" behavior on the home gallery. Each is also a fully
 * viewable/editable form in its own right (ids like `retro-2`, `retro-3`).
 */
export const EXTRA_VARIANTS: FormTemplate[] = [
  // ---------- retro ----------
  {
    id: "retro-2",
    theme: "retro",
    name: "High Score Entry",
    tagline: "Submit your arcade high score.",
    title: "NEW HIGH SCORE!",
    description: "Enter your initials for the leaderboard.",
    submitLabel: "SAVE SCORE",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "tag", type: "text", label: "Player Tag", placeholder: "AAA", required: true },
      { id: "game", type: "select", label: "Game", options: ["Pixel Dungeon", "Space Blasters", "Kart Kaos"], required: true },
      { id: "score", type: "number", label: "Score", placeholder: "999999" },
      { id: "replay", type: "checkbox", label: "Show my replay to others" },
    ],
  },
  {
    id: "retro-3",
    theme: "retro",
    name: "Boss Battle Feedback",
    tagline: "Rate the dungeon you just cleared.",
    title: "RATE THE DUNGEON",
    description: "Your feedback shapes the next quest.",
    submitLabel: "SUBMIT REVIEW",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "hero", type: "text", label: "Hero Name", placeholder: "Sir Pixelot", required: true },
      { id: "difficulty", type: "radio", label: "Difficulty", options: ["Too easy", "Just right", "Brutal"], required: true },
      { id: "boss", type: "select", label: "Favorite Boss", options: ["Slime King", "Bit Dragon", "Glitch Lord"] },
      { id: "notes", type: "textarea", label: "Comments", placeholder: "The final boss was..." },
    ],
  },
  // ---------- terminal ----------
  {
    id: "terminal-2",
    theme: "terminal",
    name: "bug_report",
    tagline: "File a bug against the mainframe.",
    title: "BUG REPORT",
    description: "Log a defect for triage.",
    submitLabel: "> SUBMIT",
    showSvgBackground: true,
    showHeaderGraphic: false,
    fields: [
      { id: "reporter", type: "text", label: "reporter", placeholder: "neo", required: true },
      { id: "severity", type: "radio", label: "severity", options: ["low", "medium", "high", "critical"], required: true },
      { id: "component", type: "select", label: "component", options: ["auth", "api", "ui", "database"] },
      { id: "trace", type: "textarea", label: "stack_trace", placeholder: "Traceback (most recent call last)..." },
    ],
  },
  {
    id: "terminal-3",
    theme: "terminal",
    name: "provision_request",
    tagline: "Spin up a new server instance.",
    title: "PROVISION SERVER",
    description: "Request compute from the cluster.",
    submitLabel: "> DEPLOY",
    showSvgBackground: true,
    showHeaderGraphic: false,
    fields: [
      { id: "hostname", type: "text", label: "hostname", placeholder: "web-01", required: true },
      { id: "region", type: "select", label: "region", options: ["us-east", "us-west", "eu-central", "ap-south"], required: true },
      { id: "cores", type: "number", label: "cpu_cores", placeholder: "4" },
      { id: "key", type: "textarea", label: "ssh_public_key", placeholder: "ssh-ed25519 AAAA..." },
    ],
  },
  // ---------- autumn ----------
  {
    id: "autumn-2",
    theme: "autumn",
    name: "Pumpkin Patch Booking",
    tagline: "Reserve a wagon at the patch.",
    title: "Pumpkin Patch Visit",
    description: "Book your family's fall outing.",
    submitLabel: "Book my visit 🎃",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", placeholder: "Autumn Leaf", required: true },
      { id: "date", type: "date", label: "Visit date" },
      { id: "group", type: "number", label: "Group size", placeholder: "4" },
      { id: "hayride", type: "checkbox", label: "Add a hayride" },
    ],
  },
  {
    id: "autumn-3",
    theme: "autumn",
    name: "Recipe Swap",
    tagline: "Share your coziest fall recipe.",
    title: "Fall Recipe Swap",
    description: "Trade a seasonal favorite with the group.",
    submitLabel: "Share recipe 🍂",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "dish", type: "text", label: "Dish name", placeholder: "Maple pecan pie" },
      { id: "category", type: "select", label: "Category", options: ["Dessert", "Main", "Drink", "Side"] },
      { id: "recipe", type: "textarea", label: "The recipe", placeholder: "Preheat oven to..." },
    ],
  },
  // ---------- nerdy ----------
  {
    id: "nerdy-2",
    theme: "nerdy",
    name: "Lab Equipment Request",
    tagline: "Request gear for your experiment.",
    title: "Equipment Request",
    description: "Reserve lab equipment for your study.",
    submitLabel: "Request equipment",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "researcher", type: "text", label: "Researcher name", required: true },
      { id: "equipment", type: "select", label: "Equipment", options: ["Microscope", "Centrifuge", "Spectrometer", "3D printer"], required: true },
      { id: "qty", type: "number", label: "Quantity", placeholder: "1" },
      { id: "why", type: "textarea", label: "Justification", placeholder: "Needed for..." },
    ],
  },
  {
    id: "nerdy-3",
    theme: "nerdy",
    name: "Study Group Sign-up",
    tagline: "Join a subject study group.",
    title: "Study Group Sign-up",
    description: "Find your people and hit the books.",
    submitLabel: "Join the group",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "subject", type: "select", label: "Subject", options: ["Calculus", "Organic Chem", "Algorithms", "Statistics"], required: true },
      { id: "avail", type: "radio", label: "Availability", options: ["Mornings", "Afternoons", "Evenings"] },
      { id: "goals", type: "textarea", label: "Your goals", placeholder: "I want to master..." },
    ],
  },
  // ---------- neon ----------
  {
    id: "neon-2",
    theme: "neon",
    name: "DJ Application",
    tagline: "Apply to spin at the next set.",
    title: "DJ APPLICATION",
    description: "Bring the synths. Apply to headline.",
    submitLabel: "Drop the beat",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "artist", type: "text", label: "Artist name", placeholder: "DJ Neon", required: true },
      { id: "genre", type: "select", label: "Genre", options: ["Synthwave", "Darkwave", "House", "Retrowave"], required: true },
      { id: "length", type: "number", label: "Set length (min)", placeholder: "60" },
      { id: "demo", type: "text", label: "Demo link", placeholder: "https://..." },
    ],
  },
  {
    id: "neon-3",
    theme: "neon",
    name: "Arcade Tournament",
    tagline: "Enter the neon arcade showdown.",
    title: "TOURNAMENT ENTRY",
    description: "Prove you're the highest scorer alive.",
    submitLabel: "Enter the arena",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "gamertag", type: "text", label: "Gamertag", placeholder: "xXNeonXx", required: true },
      { id: "game", type: "select", label: "Game", options: ["Grid Racer", "Laser Duel", "Beat Blaster"], required: true },
      { id: "skill", type: "radio", label: "Skill level", options: ["Rookie", "Pro", "Legend"] },
      { id: "trash", type: "textarea", label: "Trash talk", placeholder: "You're all going down..." },
    ],
  },
  // ---------- cosmic ----------
  {
    id: "cosmic-2",
    theme: "cosmic",
    name: "Satellite Launch",
    tagline: "Request a slot on the next rocket.",
    title: "LAUNCH REQUEST",
    description: "Book your payload a ride to orbit.",
    submitLabel: "Request launch 🛰️",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "org", type: "text", label: "Organization", required: true },
      { id: "mass", type: "number", label: "Payload mass (kg)", placeholder: "250" },
      { id: "orbit", type: "select", label: "Target orbit", options: ["LEO", "MEO", "GEO", "Lunar transfer"], required: true },
      { id: "mission", type: "textarea", label: "Mission summary", placeholder: "Earth observation..." },
    ],
  },
  {
    id: "cosmic-3",
    theme: "cosmic",
    name: "Stargazing Meetup",
    tagline: "Join the late-night sky watch.",
    title: "STARGAZING MEETUP",
    description: "Bring a blanket. We'll bring the telescopes.",
    submitLabel: "Reserve a spot ✦",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "date", type: "date", label: "Preferred night" },
      { id: "target", type: "select", label: "Most excited to see", options: ["Saturn's rings", "The Moon", "Andromeda", "Meteor shower"] },
      { id: "scope", type: "checkbox", label: "I'll bring a telescope" },
    ],
  },
  // ---------- ocean ----------
  {
    id: "ocean-2",
    theme: "ocean",
    name: "Beach Cleanup",
    tagline: "Volunteer for a shoreline cleanup.",
    title: "Cleanup Volunteer",
    description: "Help keep our reefs and beaches clean.",
    submitLabel: "Sign me up 🐚",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "email", type: "email", label: "Email", placeholder: "you@sea.org", required: true },
      { id: "beach", type: "select", label: "Location", options: ["Coral Bay", "Sunset Cove", "Turtle Beach"] },
      { id: "date", type: "date", label: "Which day?" },
    ],
  },
  {
    id: "ocean-3",
    theme: "ocean",
    name: "Aquarium Membership",
    tagline: "Become an aquarium member.",
    title: "Aquarium Membership",
    description: "Unlimited visits under the sea.",
    submitLabel: "Join today 🐠",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Full name", required: true },
      { id: "tier", type: "select", label: "Membership tier", options: ["Individual", "Family", "Patron"], required: true },
      { id: "guests", type: "number", label: "Household members", placeholder: "3" },
      { id: "news", type: "checkbox", label: "Send me tide-pool updates" },
    ],
  },
  // ---------- comic ----------
  {
    id: "comic-2",
    theme: "comic",
    name: "Villain Application",
    tagline: "Apply to join the Legion of Doom.",
    title: "VILLAIN SIGN-UP!",
    description: "Every hero needs a nemesis. Apply within.",
    submitLabel: "MWAHAHA! Apply",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "villain", type: "text", label: "Villain name", placeholder: "Doctor Doom-ish", required: true },
      { id: "power", type: "select", label: "Signature power", options: ["Mind control", "Doomsday device", "Shape-shifting", "Weather control"], required: true },
      { id: "scheme", type: "textarea", label: "Your evil scheme", placeholder: "First, I will..." },
      { id: "minions", type: "number", label: "Minions on payroll", placeholder: "50" },
    ],
  },
  {
    id: "comic-3",
    theme: "comic",
    name: "Comic Con Pass",
    tagline: "Grab your convention badge.",
    title: "GRAB YOUR PASS!",
    description: "Assemble! Register for the con.",
    submitLabel: "ZAP! Register",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "pass", type: "radio", label: "Pass type", options: ["Single day", "Weekend", "VIP"], required: true },
      { id: "cosplay", type: "checkbox", label: "I'm entering the cosplay contest" },
      { id: "hero", type: "text", label: "Favorite hero", placeholder: "Captain Comet" },
    ],
  },
  // ---------- winter ----------
  {
    id: "winter-2",
    theme: "winter",
    name: "Ski Trip Sign-up",
    tagline: "Hit the slopes with the crew.",
    title: "Ski Trip Sign-up",
    description: "Fresh powder awaits — join the trip.",
    submitLabel: "Hit the slopes ⛷️",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "skill", type: "radio", label: "Skill level", options: ["Beginner", "Intermediate", "Expert"], required: true },
      { id: "rental", type: "checkbox", label: "I need gear rental" },
      { id: "date", type: "date", label: "Preferred date" },
    ],
  },
  {
    id: "winter-3",
    theme: "winter",
    name: "Secret Santa",
    tagline: "Join the office gift exchange.",
    title: "Secret Santa",
    description: "Add your wishlist to the hat.",
    submitLabel: "Add me to the draw ❄",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "wishlist", type: "textarea", label: "Your wishlist", placeholder: "Books, cozy socks..." },
      { id: "budget", type: "select", label: "Budget", options: ["$10", "$25", "$50"] },
      { id: "allergies", type: "text", label: "Allergies / avoid", placeholder: "No nuts please" },
    ],
  },
  // ---------- birthday ----------
  {
    id: "birthday-2",
    theme: "birthday",
    name: "Cake Order",
    tagline: "Order the perfect birthday cake.",
    title: "Order a Cake! 🎂",
    description: "Tell us how to make it sweet.",
    submitLabel: "Order cake",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "flavor", type: "select", label: "Flavor", options: ["Chocolate", "Vanilla", "Funfetti", "Red velvet"], required: true },
      { id: "size", type: "radio", label: "Size", options: ["6\"", "8\"", "10\""] },
      { id: "msg", type: "text", label: "Message on cake", placeholder: "Happy Birthday!" },
    ],
  },
  {
    id: "birthday-3",
    theme: "birthday",
    name: "Gift Registry",
    tagline: "Add a gift to the registry.",
    title: "Gift Registry 🎁",
    description: "Help guests pick the perfect present.",
    submitLabel: "Add gift",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "gift", type: "text", label: "Gift idea", placeholder: "Bluetooth speaker" },
      { id: "price", type: "number", label: "Approx price ($)", placeholder: "40" },
      { id: "link", type: "text", label: "Link", placeholder: "https://..." },
    ],
  },
  // ---------- kawaii ----------
  {
    id: "kawaii-2",
    theme: "kawaii",
    name: "Plushie Adoption",
    tagline: "Adopt a little plush friend.",
    title: "Adopt a Plushie ♡",
    description: "Give a soft friend a forever home.",
    submitLabel: "Adopt me! ♡",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "plushie", type: "select", label: "Choose your plushie", options: ["Bunny", "Bear", "Kitty", "Axolotl"], required: true },
      { id: "plushname", type: "text", label: "Name your plushie", placeholder: "Mochi" },
      { id: "promise", type: "checkbox", label: "I promise lots of cuddles" },
    ],
  },
  {
    id: "kawaii-3",
    theme: "kawaii",
    name: "Bubble Tea Order",
    tagline: "Customize your boba order.",
    title: "Bubble Tea Order ♡",
    description: "Build your perfect cup.",
    submitLabel: "Order boba ♡",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Your name", required: true },
      { id: "tea", type: "select", label: "Tea base", options: ["Taro", "Matcha", "Brown sugar", "Strawberry"], required: true },
      { id: "sweet", type: "radio", label: "Sweetness", options: ["25%", "50%", "75%", "100%"] },
      { id: "toppings", type: "text", label: "Toppings", placeholder: "Pearls, pudding" },
    ],
  },
  // ---------- western ----------
  {
    id: "western-2",
    theme: "western",
    name: "Saloon Reservation",
    tagline: "Reserve a table at the saloon.",
    title: "SALOON BOOKING",
    description: "Rustle up a table for your party, partner.",
    submitLabel: "Book the table",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "name", type: "text", label: "Name", placeholder: "Dead-Eye Dan", required: true },
      { id: "party", type: "number", label: "Party size", placeholder: "4" },
      { id: "date", type: "date", label: "Date" },
      { id: "table", type: "select", label: "Seating", options: ["Bar", "Booth", "Poker table"] },
    ],
  },
  {
    id: "western-3",
    theme: "western",
    name: "Rodeo Sign-up",
    tagline: "Enter the county rodeo.",
    title: "RODEO ENTRY",
    description: "Saddle up and sign your name.",
    submitLabel: "Sign up to ride",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "rider", type: "text", label: "Rider name", required: true },
      { id: "event", type: "select", label: "Event", options: ["Bull riding", "Barrel racing", "Roping", "Bronc riding"], required: true },
      { id: "horse", type: "text", label: "Horse name", placeholder: "Thunder" },
      { id: "exp", type: "radio", label: "Experience", options: ["Greenhorn", "Seasoned", "Champion"] },
    ],
  },
  // ---------- noir ----------
  {
    id: "noir-2",
    theme: "noir",
    name: "Missing Person Report",
    tagline: "Report someone who vanished.",
    title: "MISSING PERSON",
    description: "Give us the details. We'll start looking.",
    submitLabel: "File report",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "reporter", type: "text", label: "Your name", required: true },
      { id: "person", type: "text", label: "Missing person's name", required: true },
      { id: "seen", type: "date", label: "Last seen" },
      { id: "desc", type: "textarea", label: "Description", placeholder: "Tall, wore a grey coat..." },
    ],
  },
  {
    id: "noir-3",
    theme: "noir",
    name: "Anonymous Tip",
    tagline: "Slip us a tip on a case.",
    title: "SUBMIT A TIP",
    description: "The city's counting on you, kid.",
    submitLabel: "Send the tip",
    showSvgBackground: true,
    showHeaderGraphic: true,
    fields: [
      { id: "alias", type: "text", label: "Alias", placeholder: "The Shadow" },
      { id: "case", type: "select", label: "Related case", options: ["The Harbor Heist", "The Vanishing", "The Double-Cross"], required: true },
      { id: "tip", type: "textarea", label: "Your tip", placeholder: "I saw something down by the docks...", required: true },
      { id: "anon", type: "checkbox", label: "Keep me anonymous" },
    ],
  },
];

/** Every form: the 13 primary templates followed by their extra variants. */
export const ALL_FORMS: FormTemplate[] = [...TEMPLATES, ...EXTRA_VARIANTS];

export function getTemplate(id: string): FormTemplate | undefined {
  return ALL_FORMS.find((t) => t.id === id);
}

/** All variants that share a theme, primary template first. */
export function getVariants(theme: FormTemplate["theme"]): FormTemplate[] {
  return ALL_FORMS.filter((t) => t.theme === theme);
}
