"use client";

import { useEffect, useState } from "react";
import { FormField, FormTemplate, GeneratedTheme } from "@/lib/types";
import Confetti from "./decorations/Confetti";

const RADIUS: Record<GeneratedTheme["radius"], string> = {
  sharp: "0px",
  soft: "12px",
  round: "22px",
};

const FONT_CLASS: Record<GeneratedTheme["font"], string> = {
  sans: "font-sans",
  serif: "font-serif",
  mono: "font-mono",
  rounded: "font-rounded",
};

interface Props {
  form: FormTemplate;
  mode: "fill" | "preview";
}

/** Renders a form with a Claude-generated theme (design tokens, no preset). */
export default function CustomThemedForm({ form, mode }: Props) {
  const t = form.customTheme!;
  const [values, setValues] = useState<Record<string, string | boolean>>({});
  const [submitted, setSubmitted] = useState(false);

  const rootStyle = {
    "--cf-card-bg": t.cardBg,
    "--cf-card-border": t.cardBorder,
    "--cf-text": t.text,
    "--cf-title": t.title,
    "--cf-muted": t.muted,
    "--cf-accent": t.accent,
    "--cf-accent-text": t.accentText,
    "--cf-input-bg": t.inputBg,
    "--cf-input-border": t.inputBorder,
    "--cf-radius": RADIUS[t.radius],
    background: `linear-gradient(160deg, ${t.pageFrom}, ${t.pageTo})`,
  } as React.CSSProperties;

  function set(id: string, v: string | boolean) {
    setValues((p) => ({ ...p, [id]: v }));
  }
  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (mode === "fill") setSubmitted(true);
  }

  return (
    <div
      style={rootStyle}
      className={`relative w-full overflow-hidden px-4 py-14 ${FONT_CLASS[t.font]}`}
    >
      {form.showSvgBackground && <CustomBackdrop kind={t.backdrop} />}

      <div className="relative z-10 mx-auto max-w-xl">
        <form
          onSubmit={onSubmit}
          className="cf-card px-6 py-8 shadow-2xl md:px-10"
        >
          {form.showHeaderGraphic && (
            <div className="mb-3 text-center text-5xl">{t.emoji}</div>
          )}

          <h1 className="cf-title mb-2 text-center text-2xl font-bold md:text-3xl">
            {form.title}
          </h1>
          <p className="cf-muted mb-8 text-center">{form.description}</p>

          {submitted ? (
            <div className="animate-float-up py-10 text-center">
              <div className="mb-3 text-4xl">{t.emoji}</div>
              <p className="cf-title mb-2 text-xl font-semibold">Thank you!</p>
              <p className="cf-muted mb-6">Your response was captured (in memory).</p>
              <button
                onClick={() => setSubmitted(false)}
                className="cf-btn px-6 py-2"
              >
                Fill again
              </button>
            </div>
          ) : (
            <div className="space-y-6">
              {form.fields.map((field) => (
                <Field
                  key={field.id}
                  field={field}
                  accent={t.accent}
                  value={values[field.id]}
                  disabled={mode === "preview"}
                  onChange={(v) => set(field.id, v)}
                />
              ))}
              <button type="submit" className="cf-btn mt-2 w-full px-6 py-3">
                {form.submitLabel}
              </button>
              {mode === "preview" && (
                <p className="cf-muted text-center text-xs opacity-70">
                  Preview only — try the live version from the “Fill out” view.
                </p>
              )}
            </div>
          )}
        </form>

        <p className="cf-muted mt-4 text-center text-xs opacity-60">
          ✨ {t.name} · generated by Claude
        </p>
      </div>
    </div>
  );
}

function Field({
  field,
  accent,
  value,
  disabled,
  onChange,
}: {
  field: FormField;
  accent: string;
  value: string | boolean | undefined;
  disabled: boolean;
  onChange: (v: string | boolean) => void;
}) {
  const req = field.required ? <span style={{ color: "#ef4444" }}> *</span> : null;

  if (field.type === "checkbox") {
    return (
      <label className="cf-label flex cursor-pointer items-center gap-3">
        <input
          type="checkbox"
          checked={Boolean(value)}
          disabled={disabled}
          onChange={(e) => onChange(e.target.checked)}
          style={{ accentColor: accent }}
          className="h-5 w-5"
        />
        {field.label}
        {req}
      </label>
    );
  }

  return (
    <div>
      <label className="cf-label mb-2 block">
        {field.label}
        {req}
      </label>

      {field.type === "textarea" && (
        <textarea
          className="cf-input min-h-[96px] resize-y"
          placeholder={field.placeholder}
          required={field.required}
          disabled={disabled}
          value={(value as string) ?? ""}
          onChange={(e) => onChange(e.target.value)}
        />
      )}

      {field.type === "select" && (
        <select
          className="cf-input"
          required={field.required}
          disabled={disabled}
          value={(value as string) ?? ""}
          onChange={(e) => onChange(e.target.value)}
        >
          <option value="">— choose —</option>
          {field.options?.map((o) => (
            <option key={o} value={o}>
              {o}
            </option>
          ))}
        </select>
      )}

      {field.type === "radio" && (
        <div className="space-y-2">
          {field.options?.map((o) => (
            <label key={o} className="cf-label flex cursor-pointer items-center gap-2">
              <input
                type="radio"
                name={field.id}
                value={o}
                disabled={disabled}
                checked={value === o}
                onChange={() => onChange(o)}
                style={{ accentColor: accent }}
                className="h-4 w-4"
              />
              {o}
            </label>
          ))}
        </div>
      )}

      {["text", "email", "number", "date"].includes(field.type) && (
        <input
          type={field.type}
          className="cf-input"
          placeholder={field.placeholder}
          required={field.required}
          disabled={disabled}
          value={(value as string) ?? ""}
          onChange={(e) => onChange(e.target.value)}
        />
      )}
    </div>
  );
}

/* ---------- decorative backdrop for custom themes ---------- */
function CustomBackdrop({ kind }: { kind: GeneratedTheme["backdrop"] }) {
  const [stars, setStars] = useState<
    { id: number; left: number; top: number; size: number; delay: number; dur: number }[]
  >([]);

  useEffect(() => {
    if (kind !== "stars") return;
    setStars(
      Array.from({ length: 50 }, (_, i) => ({
        id: i,
        left: Math.random() * 100,
        top: Math.random() * 100,
        size: 1 + Math.random() * 2.5,
        delay: Math.random() * 4,
        dur: 2 + Math.random() * 3,
      }))
    );
  }, [kind]);

  if (kind === "none") return null;
  if (kind === "confetti") return <Confetti />;

  if (kind === "dots") return <div className="cf-bg-dots absolute inset-0 z-0" />;
  if (kind === "grid") return <div className="cf-bg-grid absolute inset-0 z-0" />;

  if (kind === "stars") {
    return (
      <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden">
        {stars.map((s) => (
          <span
            key={s.id}
            className="absolute rounded-full"
            style={{
              left: `${s.left}%`,
              top: `${s.top}%`,
              width: s.size,
              height: s.size,
              background: "var(--cf-accent)",
              animation: `twinkle ${s.dur}s ease-in-out ${s.delay}s infinite`,
            }}
          />
        ))}
      </div>
    );
  }

  if (kind === "waves") {
    return (
      <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden">
        <svg className="absolute inset-x-0 bottom-0 h-full w-full" preserveAspectRatio="none" viewBox="0 0 800 600" style={{ color: "var(--cf-accent)" }}>
          <path d="M0 480 Q200 430 400 480 T800 470 V600 H0 Z" fill="currentColor" opacity="0.12" />
          <path d="M0 520 Q200 480 400 520 T800 515 V600 H0 Z" fill="currentColor" opacity="0.18" />
        </svg>
      </div>
    );
  }

  // rays
  return (
    <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden">
      <svg className="h-full w-full" preserveAspectRatio="xMidYMid slice" viewBox="0 0 800 600" style={{ color: "var(--cf-accent)" }}>
        {Array.from({ length: 12 }).map((_, i) => {
          const a = (i / 12) * Math.PI * 2;
          return (
            <line
              key={i}
              x1={400}
              y1={140}
              x2={Math.round(400 + Math.cos(a) * 1000)}
              y2={Math.round(140 + Math.sin(a) * 1000)}
              stroke="currentColor"
              strokeWidth="60"
              opacity="0.04"
            />
          );
        })}
      </svg>
    </div>
  );
}
